### ISSUE TITLE
Add ability to search for cover art for selected albums and tracks to the `Search Engine Lookup` plugin

### ISSUE THREAD

**Issue by leeuniverse** [rdswift/picard-plugins#3] opened 2021-09-29 23:20 UTC
Hi, thanks for your plugin, unfortunately, it doesn't do quite what I'm needing, so I need your help in that per requested at the MusicBrainz Picard Forum...

I've created a post there showing exactly what I'm needing done (which includes a Video Demo I created).

https://community.metabrainz.org/t/feature-request-add-search-engine-album-link-video-demonstrating/552915

If you could help that would be great....  Thanks much.

**Comment by rdswift** [comment] 2021-09-30 16:18
What plugin are you suggesting be changed?  I had a look at your video and it seems to only be about album art lookup.  I have not developed any plugins dealing with album coverart, so I'm not sure what you're asking of me.

**Comment by leeuniverse** [comment] 2021-09-30 16:21
Huh, that's weird...  MusicBrainz Picard has you listed as developing the Plugin "Search Engine Lookup 2.0.2" as listed here: https://picard.musicbrainz.org/plugins/

Also, you're listed here on GitHub as having developed it, that's how I got here?
Okay, now I'm confused, not finding this plugin associated with your name on GitHub anymore?  That's weird.
Is there a different Bob Swift who did the Search Engine Lookup Plugin?

**Comment by rdswift** [comment] 2021-09-30 16:44
I'd forgotten about that one, and in any event it provides a lookup on the album information from a cluster and not specific track coverart.  I don't want to modify the basic functionality of the plugin because that would break it for people that already use it as intended.  I will take a look and see it I can extend the functionality to also provide specific lookups for album and track cover art.

**Comment by leeuniverse** [comment] 2021-09-30 16:47
Yes, I saw that it does similar stuff that I'm needing, but certainly needing to be extended some, so if you could extend it in whatever way you can per my information that would be great...

Much appreciated, thank you...

**Comment by rdswift** [comment] 2021-10-01 00:26
I've updated the plugin locally and submitted a pull request to update the master list for Picard.  https://github.com/metabrainz/picard-plugins/pull/312

You can either wait until the changes have been merged into the master and show up as an available update in Picard's plugins option menu, or you can download it from my repository and install it manually.  https://github.com/rdswift/picard-plugins/tree/2.0_RDS_Plugins/plugins/search_engine_lookup

**Comment by leeuniverse** [comment] 2021-10-01 00:28
Wow, that was fast...  I'll see if I can install it and will test it and give you any thoughts.
Thanks much...  :)

**Comment by rdswift** [comment] 2021-10-01 00:29
> Wow, that was fast... I'll see if I can install it and will test it and give you any thoughts.

Note that you will likely need to uninstall the current version and delete it before installing the new version.

**Comment by leeuniverse** [comment] 2021-10-01 00:48
Great, it worked...  :)
One suggestion for improvement.  Could you have it directly go to the "Image" Tab of Google and the other Search Engines?
I believe there's a way to format the search link to do that.

Thanks  :)

**Comment by rdswift** [comment] 2021-10-01 15:30
> One suggestion for improvement. Could you have it directly go to the "Image" Tab of Google and the other Search Engines?
> I believe there's a way to format the search link to do that.

There is, however each search site does it differently, so there's no way to implement it other than having the user define the image search URL template for each provider defined.  For now it appears that you're stuck with one extra mouse click.

**Closed as completed** 2021-10-01 15:30 UTC

**Comment by leeuniverse** [comment] 2021-10-01 19:31
So...  I understand each site does the search differently, but aren't you designating the search url already for each site to make it work, thus can't you just change the url to select the Image tab for that particular search engine, or if you can't do it for "all" of them, I believe you can at least do it for Google?

Also, one other feature I would like to see for further improvement....
Could you allow ALL Search Engines to be "checked" in settings (what ones we want to check) for those of us who are fine with multiple Tabs popping up in our browser?  Currently, we can only select ONE search engine to search.

Sometimes one search engine doesn't have the image we need but another does.  Pretty Please...  Thanks again.  :)
